name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  non-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry # ignored non-windows
      - uses: perl-actions/install-with-cpanm@v1
        with:
          args: -n --installdeps --with-recommends .
      - run: perl -V
      - name: Run tests
        run: |
          perl Makefile.PL
          gmake
          prove -brj4 t
  darwin:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: brew install perl libomp
      - name: perl -V
        run: perl -V
      - uses: perl-actions/install-with-cpanm@v1
        with:
          args: -n --installdeps --with-recommends .
          sudo: false
      - name: Run Tests
        run: |
          perl Makefile.PL
          make
          prove -brv t xt
